name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create missing index.html
      run: |
        echo "Creating index.html for mobile build..."
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
            <title>Step Up Naija - #13K Credible Challenge</title>
            <meta name="description" content="Join millions of Nigerians in the #13K Credible Challenge. Nominate credible leaders, participate in civic activities, and build Nigeria's future." />
            <link rel="icon" type="image/x-icon" href="/favicon.ico" />
          </head>
          <body>
            <div id="root"></div>
            <script type="module" src="/src/main.tsx"></script>
          </body>
        </html>
        EOF
    
    - name: Verify assets and fix imports
      run: |
        echo "Verifying asset files exist and fixing component imports..."
        
        # Verify critical asset exists
        if [ -f "attached_assets/generated_images/Nigerian_youth_civic_engagement_scene_024f101a.png" ]; then
          echo "✅ Critical asset file exists: Nigerian_youth_civic_engagement_scene_024f101a.png"
        else
          echo "❌ Critical asset missing - creating placeholder..."
          mkdir -p attached_assets/generated_images
          echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" | base64 -d > "attached_assets/generated_images/Nigerian_youth_civic_engagement_scene_024f101a.png"
        fi
        
        # Fix component import issues
        if [ -f "src/pages/community-chat.tsx" ]; then
          sed -i 's/RealtimeNotifications/RealTimeNotifications/g' src/pages/community-chat.tsx
          sed -i 's/@\/components\/RealtimeNotifications/@\/components\/RealTimeNotifications/g' src/pages/community-chat.tsx
          echo "✅ Fixed community-chat.tsx imports"
        fi
        
        # Fix client-side imports
        if [ -f "client/src/pages/community-chat.tsx" ]; then
          sed -i 's/RealtimeNotifications/RealTimeNotifications/g' client/src/pages/community-chat.tsx
          sed -i 's/@\/components\/RealtimeNotifications/@\/components\/RealTimeNotifications/g' client/src/pages/community-chat.tsx
          echo "✅ Fixed client community-chat.tsx imports"
        fi
        
        echo "✅ Asset verification and import fixes complete!"
    
    - name: Build web app
      run: |
        echo "Building web app..."
        npx vite build --config vite.config.mobile.ts
        
        # Move build files to correct location for Capacitor
        if [ -d "dist/public" ]; then
          rm -rf build 2>/dev/null || true
          mv dist/public build
        elif [ -d "dist" ]; then
          rm -rf build 2>/dev/null || true
          mv dist build
        fi
        
        # Ensure Capacitor can find web assets
        mkdir -p dist
        cp -r build dist/public
    
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli@latest
    
    - name: Add Android platform
      run: |
        npx cap add android
        npx cap copy android
        npx cap sync android
    
    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: step-up-naija-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    - name: Display APK info
      run: |
        echo "✅ Step Up Naija Android APK built successfully!"
        echo "📱 Location: android/app/build/outputs/apk/debug/app-debug.apk"
        ls -la android/app/build/outputs/apk/debug/
