name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create missing index.html
      run: |
        echo "Creating index.html for mobile build..."
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
            <title>Step Up Naija - #13K Credible Challenge</title>
            <meta name="description" content="Join millions of Nigerians in the #13K Credible Challenge. Nominate credible leaders, participate in civic activities, and build Nigeria's future." />
            <link rel="icon" type="image/x-icon" href="/favicon.ico" />
          </head>
          <body>
            <div id="root"></div>
            <script type="module" src="/src/main.tsx"></script>
          </body>
        </html>
        EOF
    
    - name: Fix missing assets and imports
      run: |
        echo "Creating comprehensive mobile build fixes..."
        mkdir -p attached_assets/generated_images
        
        # Install ImageMagick for creating proper PNG files
        sudo apt-get update -qq
        sudo apt-get install -y imagemagick
        
        # Create PNG placeholder function using ImageMagick
        create_png_placeholder() {
          echo "Creating placeholder: $1"
          # Create a 100x100 transparent PNG with ImageMagick
          magick -size 100x100 xc:transparent "$1" 2>/dev/null
          if [ ! -f "$1" ] || [ ! -s "$1" ]; then
            # Fallback: use convert command
            convert -size 100x100 xc:transparent "$1" 2>/dev/null
          fi
          if [ ! -f "$1" ] || [ ! -s "$1" ]; then
            # Fallback: create using base64
            echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==" | base64 -d > "$1" 2>/dev/null
          fi
        }
        
        # Fix problematic asset imports by replacing them with data URIs
        echo "Fixing import issues and asset imports..."
        
        # Create a simple 1x1 transparent PNG as data URI
        PLACEHOLDER_IMAGE_DATA="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg=="
        
        # Fix community-chat.tsx imports
        if [ -f "src/pages/community-chat.tsx" ]; then
          sed -i 's/RealtimeNotifications/RealTimeNotifications/g' src/pages/community-chat.tsx
          sed -i 's/@\/components\/RealtimeNotifications/@\/components\/RealTimeNotifications/g' src/pages/community-chat.tsx
          echo "Fixed community-chat.tsx imports"
        fi
        
        # Fix client-side imports
        if [ -f "client/src/pages/community-chat.tsx" ]; then
          sed -i 's/RealtimeNotifications/RealTimeNotifications/g' client/src/pages/community-chat.tsx
          sed -i 's/@\/components\/RealtimeNotifications/@\/components\/RealTimeNotifications/g' client/src/pages/community-chat.tsx
          echo "Fixed client community-chat.tsx imports"
        fi
        
        # Replace problematic asset imports in landing-comprehensive.tsx
        if [ -f "client/src/pages/landing-comprehensive.tsx" ]; then
          echo "Fixing asset imports in landing-comprehensive.tsx..."
          # Replace asset imports with inline data URIs
          sed -i 's|import youthEngagementImage from "@assets/generated_images/Nigerian_youth_civic_engagement_scene_024f101a.png";|const youthEngagementImage = "'"$PLACEHOLDER_IMAGE_DATA"'";|g' client/src/pages/landing-comprehensive.tsx
          sed -i 's|import youthLeadershipImage from "@assets/generated_images/Nigerian_youth_leadership_action_scene_a4fe4b9b.png";|const youthLeadershipImage = "'"$PLACEHOLDER_IMAGE_DATA"'";|g' client/src/pages/landing-comprehensive.tsx
          sed -i 's|import drRasheedImage from "@assets/generated_images/Nigerian_executive_director_headshot_66d7aed0.png";|const drRasheedImage = "'"$PLACEHOLDER_IMAGE_DATA"'";|g' client/src/pages/landing-comprehensive.tsx
          sed -i 's|import aishaImage from "@assets/generated_images/Nigerian_program_director_headshot_e243da1e.png";|const aishaImage = "'"$PLACEHOLDER_IMAGE_DATA"'";|g' client/src/pages/landing-comprehensive.tsx
          sed -i 's|import emmanuelImage from "@assets/generated_images/Nigerian_tech_director_headshot_f21fc2b5.png";|const emmanuelImage = "'"$PLACEHOLDER_IMAGE_DATA"'";|g' client/src/pages/landing-comprehensive.tsx
          sed -i 's|import sarahImage from "@assets/generated_images/Nigerian_community_relations_headshot_1fca20ac.png";|const sarahImage = "'"$PLACEHOLDER_IMAGE_DATA"'";|g' client/src/pages/landing-comprehensive.tsx
          echo "✅ Fixed landing-comprehensive.tsx asset imports"
        fi
        
        # Also fix any other problematic asset imports
        find client/src -name "*.tsx" -exec grep -l "@assets/generated_images" {} \; 2>/dev/null | while read file; do
          echo "Fixing asset imports in: $file"
          sed -i 's|import .* from "@assets/generated_images/[^"]*";|const placeholderImage = "'"$PLACEHOLDER_IMAGE_DATA"'";|g' "$file"
        done
        
        # Create all missing assets with placeholders
        all_assets=(
          "primary-logo_1756495358509.png"
          "primary-logo.png" 
          "Untitled design-4_1757162712832.png"
          "tari-avatar.webp"
          "kamsi-avatar.webp"
          "a8accb1294c8498f8139dafc387a47e0_1757182966452.webp"
          "kamsi_1757182966454.png"
          "generated_images/Nigerian_woman_professional_headshot_b062e128.png"
          "generated_images/Nigerian_man_professional_headshot_671c9909.png"
          "generated_images/Nigerian_academic_woman_portrait_2110a518.png"
          "generated_images/Nigerian_young_professional_headshot_5f929c22.png"
          "generated_images/Nigerian_youth_civic_engagement_scene_024f101a.png"
          "generated_images/Nigerian_youth_leadership_action_scene_a4fe4b9b.png"
          "generated_images/Nigerian_executive_director_headshot_66d7aed0.png"
          "generated_images/Nigerian_program_director_headshot_e243da1e.png"
          "generated_images/Nigerian_tech_director_headshot_f21fc2b5.png"
          "generated_images/Nigerian_community_relations_headshot_1fca20ac.png"
          "generated_images/Ogun_farmers_cooperative_facility_c3448180.png"
          "generated_images/Rivers_youth_skill_training_center_5a73d8af.png"
          "generated_images/Lagos_clean_water_project_impact_a203262d.png"
          "generated_images/Abuja_school_technology_lab_students_47624343.png"
          "generated_images/Cross_River_road_construction_project_969e2349.png"
          "generated_images/Kano_solar_health_clinic_installation_aa20defb.png"
          "generated_images/University_of_Ibadan_logo_b36b851a.png"
          "generated_images/UNILAG_university_logo_2f8621ab.png"
          "generated_images/ABU_university_logo_dfea4cfe.png"
          "generated_images/UNN_university_logo_f3e99836.png"
          "generated_images/Covenant_University_logo_796d63b3.png"
          "generated_images/OAU_university_logo_c5878c86.png"
          "generated_images/UNILORIN_university_logo_110e2837.png"
          "generated_images/FUTA_university_logo_0104532e.png"
          "generated_images/BUK_university_logo_08e474bb.png"
          "generated_images/UNIBEN_university_logo_c84ef7a6.png"
          "generated_images/LASU_university_logo_16d6bf88.png"
          "generated_images/UNIPORT_university_logo_e90409d0.png"
          "generated_images/FUTMINNA_university_logo_28d3b1e7.png"
          "generated_images/NAU_university_logo_fcccd8c1.png"
          "generated_images/UNICAL_university_logo_71674d48.png"
          "generated_images/UNIJOS_university_logo_929df0fc.png"
          "generated_images/FUNAAB_university_logo_ae46856d.png"
          "generated_images/UNIABUJA_university_logo_382b3f47.png"
          "generated_images/RSU_university_logo_08c2005f.png"
          "generated_images/AAUA_university_logo_92def4fc.png"
        )
        
        echo "Creating missing asset files..."
        for asset in "${all_assets[@]}"; do
          asset_path="attached_assets/$asset"
          if [ ! -f "$asset_path" ]; then
            echo "Creating missing asset: $asset_path"
            mkdir -p "attached_assets/$(dirname "$asset")"
            create_png_placeholder "$asset_path"
            
            # Verify file was created
            if [ -f "$asset_path" ]; then
              echo "✅ Created: $asset_path ($(stat -c%s "$asset_path") bytes)"
            else
              echo "❌ Failed to create: $asset_path"
            fi
          else
            echo "✅ Already exists: $asset_path"
          fi
        done
        
        # List created assets for verification
        echo "Final asset check:"
        ls -la attached_assets/ 2>/dev/null || echo "No attached_assets directory"
        ls -la attached_assets/generated_images/ 2>/dev/null || echo "No generated_images directory"
    
    - name: Build web app
      run: |
        echo "Building web app..."
        npx vite build --config vite.config.mobile.ts
        
        # Move build files to correct location for Capacitor
        if [ -d "dist/public" ]; then
          rm -rf build 2>/dev/null || true
          mv dist/public build
        elif [ -d "dist" ]; then
          rm -rf build 2>/dev/null || true
          mv dist build
        fi
        
        # Ensure Capacitor can find web assets
        mkdir -p dist
        cp -r build dist/public
    
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli@latest
    
    - name: Add Android platform
      run: |
        npx cap add android
        npx cap copy android
        npx cap sync android
    
    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: step-up-naija-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    - name: Display APK info
      run: |
        echo "✅ Step Up Naija Android APK built successfully!"
        echo "📱 Location: android/app/build/outputs/apk/debug/app-debug.apk"
        ls -la android/app/build/outputs/apk/debug/
