workflows:
  step-up-naija-workflow:
    name: Step Up Naija Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        # Public variables
        CAPACITOR_CLI_NO_TELEMETRY: true
      node: 18.17.0
      npm: 9
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Create missing index.html
        script: |
          echo "Creating index.html for mobile build..."
          echo '<!DOCTYPE html>' > index.html
          echo '<html lang="en">' >> index.html
          echo '  <head>' >> index.html
          echo '    <meta charset="UTF-8" />' >> index.html
          echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />' >> index.html
          echo '    <title>Step Up Naija - #13K Credible Challenge</title>' >> index.html
          echo '    <meta name="description" content="Join millions of Nigerians in the #13K Credible Challenge. Nominate credible leaders, participate in civic activities, and build Nigeria'\''s future." />' >> index.html
          echo '    <link rel="icon" type="image/x-icon" href="/favicon.ico" />' >> index.html
          echo '  </head>' >> index.html
          echo '  <body>' >> index.html
          echo '    <div id="root"></div>' >> index.html
          echo '    <script type="module" src="/src/main.tsx"></script>' >> index.html
          echo '  </body>' >> index.html
          echo '</html>' >> index.html
          ls -la index.html
          echo "index.html created successfully!"
      - name: Fix missing assets
        script: |
          echo "Creating comprehensive asset fixes for mobile build..."
          mkdir -p attached_assets
          mkdir -p attached_assets/generated_images
          
          echo "Available assets:"
          ls -la attached_assets/ | head -10
          
          # Fix primary logo (most critical) - simple reliable approach
          if [ ! -f "attached_assets/primary-logo_1756495358509.png" ]; then
            echo "Creating primary logo placeholder..."
            # Use base64 to create a valid 1x1 PNG image
            echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChAI9jU77UwAAAABJRU5ErkJggg==" | base64 -d > "attached_assets/primary-logo_1756495358509.png"
            echo "Primary logo placeholder created successfully"
            ls -la "attached_assets/primary-logo_1756495358509.png"
          else
            echo "Primary logo already exists"
          fi
          
          # Create a simple function for creating PNG placeholders
          create_png_placeholder() {
            echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChAI9jU77UwAAAABJRU5ErkJggg==" | base64 -d > "$1"
          }
          
          # Create a simple function for creating WEBP placeholders
          create_webp_placeholder() {
            # Use PNG placeholder for WEBP (most build systems can handle this)
            create_png_placeholder "$1"
          }
          
          # Fix avatar images
          if [ ! -f "attached_assets/a8accb1294c8498f8139dafc387a47e0_1757182966452.webp" ]; then
            if [ -f "attached_assets/62a53708d7f149f587b5065cdc755429_1757102170162.webp" ]; then
              cp "attached_assets/62a53708d7f149f587b5065cdc755429_1757102170162.webp" "attached_assets/a8accb1294c8498f8139dafc387a47e0_1757182966452.webp"
            else
              create_webp_placeholder "attached_assets/a8accb1294c8498f8139dafc387a47e0_1757182966452.webp"
            fi
            echo "Tari avatar placeholder created"
          fi
          
          if [ ! -f "attached_assets/kamsi_1757182966454.png" ]; then
            if [ -f "attached_assets/Kamsi bi_1757182570845.png" ]; then
              cp "attached_assets/Kamsi bi_1757182570845.png" "attached_assets/kamsi_1757182966454.png"
            else
              create_png_placeholder "attached_assets/kamsi_1757182966454.png"
            fi
            echo "Kamsi avatar placeholder created"
          fi
          
          # Create missing standard assets
          assets_to_create="primary-logo.png tari-avatar.webp kamsi-avatar.webp"
          for asset in $assets_to_create; do
            if [ ! -f "attached_assets/$asset" ]; then
              echo "Creating placeholder for $asset"
              if [[ $asset == *.png ]]; then
                create_png_placeholder "attached_assets/$asset"
              else
                create_webp_placeholder "attached_assets/$asset"
              fi
            fi
          done
          
          # Create generated_images placeholders
          generated_images="Nigerian_woman_professional_headshot_b062e128.png Nigerian_man_professional_headshot_671c9909.png Nigerian_academic_woman_portrait_2110a518.png Nigerian_young_professional_headshot_5f929c22.png Nigerian_youth_civic_engagement_scene_024f101a.png Nigerian_youth_leadership_action_scene_a4fe4b9b.png Nigerian_executive_director_headshot_66d7aed0.png Nigerian_program_director_headshot_e243da1e.png Nigerian_tech_director_headshot_f21fc2b5.png Nigerian_community_relations_headshot_1fca20ac.png"
          
          for img in $generated_images; do
            if [ ! -f "attached_assets/generated_images/$img" ]; then
              echo "Creating placeholder for generated_images/$img"
              create_png_placeholder "attached_assets/generated_images/$img"
            fi
          done
          
          echo "Comprehensive asset fix completed!"
          echo "Available assets now:"
          ls -la attached_assets/ | head -5
          ls -la attached_assets/generated_images/ | head -5 || echo "No generated_images folder yet"
      - name: Build web app
        script: |
          echo "Starting Vite build..."
          npx vite build --config vite.config.mobile.ts
      - name: Update dependencies and build Capacitor iOS
        script: |
          npx cap sync ios
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --archive-flags="-destination 'generic/platform=iOS'"
      - name: Update dependencies and build Capacitor Android
        script: |
          npx cap sync android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - build/ios/ipa/*.ipa
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - stepupnaija@example.com
        notify:
          success: true
          failure: true
      # app_store_connect:
        # api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        # key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        # issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        # submit_to_testflight: false
        # beta_groups:
          # - App Store Connect Users
      # google_play:
        # credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        # track: internal