workflows:
  step-up-naija-workflow:
    name: Step Up Naija Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        # Public variables
        CAPACITOR_CLI_NO_TELEMETRY: true
      node: 18.17.0
      npm: 9
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          echo "=== Detecting project structure ==="
          if [ -d "client" ]; then
            echo "✅ Found client/ folder"
            ls -la client/
          else
            echo "❌ No client/ folder found"
          fi
          
          if [ -d "src" ]; then
            echo "✅ Found src/ folder in root"
            ls -la src/ | head -10
          else
            echo "❌ No src/ folder in root"
          fi
          
          echo "=== Looking for index.html ==="
          find . -name "index.html" -type f | head -5
          
          echo "=== Starting build ==="
          npx vite build --config vite.config.mobile.ts
      - name: Update dependencies and build Capacitor iOS
        script: |
          npx cap sync ios
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --archive-flags="-destination 'generic/platform=iOS'"
      - name: Update dependencies and build Capacitor Android
        script: |
          npx cap sync android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - build/ios/ipa/*.ipa
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - stepupnaija@example.com
        notify:
          success: true
          failure: true
      # app_store_connect:
        # api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        # key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        # issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        # submit_to_testflight: false
        # beta_groups:
          # - App Store Connect Users
      # google_play:
        # credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        # track: internal